fix/ICE-1010-improvement js docs gh pages

diff --git a/.github/workflows/deploy-js-docs.yml b/.github/workflows/deploy-js-docs.yml
--- a/.github/workflows/deploy-js-docs.yml
+++ b/.github/workflows/deploy-js-docs.yml
@@ -56,14 +56,14 @@
          - name: Fetch all branches
            run: git fetch --all
 
-         - name: Clean up existing files
-           run: |
-             git checkout gh-pages
-             git pull origin gh-pages
-             rm -rf *
-             git add .
-             git commit -m 'Clean up old files' || true
-             git push origin gh-pages || true
+         # - name: Clean up existing files
+         #   run: |
+         #     git checkout gh-pages
+         #     git pull origin gh-pages
+         #     rm -rf *
+         #     git add .
+         #     git commit -m 'Clean up old files' || true
+         #     git push origin gh-pages || true
 
          - name: Deploy to GitHub Pages
            run: |
